apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-yioqizho
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-yioqizho:721b42675d6fed4dcbe7d75cfb96959f2af1f116@sha256:2037575745eaa292b0fbe01da62ef747b912fad314ea110da2552dba3144d141
          name: container-image
